### ISSUE TITLE
Signing into Hacker News via Octal

### ISSUE THREAD

**Issue by ZebraDude** [dangwu/Octal#100]
I just downloaded and purchased the premium IAP. 

I am unable to sign into Hacker News VIA Octal. I am on a Xs Max running iOS 12.4.1
![805F637F-31EC-47CE-83AF-3398F50DDE14](https://user-images.githubusercontent.com/55329775/64912829-666b8000-d6fa-11e9-877f-0c4dfb30998a.png)

**Comment by dangwu** [comment]
Investigating. I’m seeing this too. I believe it’s because HN recently
added a CAPTCHA.

**Comment by mttjj** [comment]
Following… I’m seeing the same thing. Was chalking it up to me running iOS 13 but sounds like that’s not the issue.

**Comment by dangwu** [comment]
I have a fix in review. Thanks for letting me know! ETA 24-48 hours.

**Comment by dangwu** [comment]
v3.9.0 is out now and fixes this issue. Sign in is now via webview in order to include the new CAPTCHA phase.

**Comment by ZebraDude** [comment]
Ah Thank you for the quick fix. The update fixed the issue

**Comment by skilfullycurled** [comment]
First, thanks for this wonderful app!  Despite the limitations from my current login issue I’m really enjoying simply using it to read.  

I think I might be having the same Captcha based login issue since the web based version requires me to perform one.  Oddly, I only receive the captcha in the browser on iOS and iPadOS but not on macOS.  Either way, I am not seeing the fix described above where Octal displays the webview to sign-in (at least I don’t think it is, screenshot attached).

Please let me know if there is any other information I can provide or if I should contact HN.  Perhaps the issue is on their end given the differences in the web based logins between the OS’s.

iOS, 13.3.1
iPad OS, v13.5.1

<img width="784" alt="Screenshot 2020-07-12 at 12 33 19 PM" src="https://user-images.githubusercontent.com/950291/87251847-ae535480-c43c-11ea-84bd-0b15708e6448.png">

**Comment by dangwu** [comment]
Thanks for the feedback and detailed info! I think I know what I can do for
you and others who might have this issue... Give me some time to update the
app. I’ll add an option to login via a web view which should show the
captcha as well.

**Comment by dangwu** [comment]
@skilfullycurled you should be able to sign in now. I've reverted a flag that allows sign in via webview now, which should include any CAPTCHAs. Force kill the app and restart it if it's an active process.

**Comment by skilfullycurled** [comment]
@dangwu, thank you so much!  I really appreciate it, and the quick turn around.  I know you're the only person who works on it and it's really great how many features there are already for a tip based (and very reasonably priced non-subscription premium) app.  I would not have thought poorly of you if this already closed issue was at the bottom of your priority list, or even a "won't fix".

PS: Let me know if you think I should check in with HN about this.  It seems weird to me that you were able to close this ten months ago without any issues since.

Thanks again!

**Comment by skilfullycurled** [comment]
Good news: I'm able to log-in!

Confusing news: I'm not getting the captcha anymore so it's hard to tell if it "worked".  

But the login does look different, so it's definitely bringing up the webview.  I'll report back with any useful diagnostic information if it occurs again.  For now, I've been wanting to use the app while logged in for so long that I don't want to ruin the moment.

Thanks again!
