### ISSUE TITLE
[Bug] Old posts are shown after refresh 

### ISSUE THREAD

**Issue by josephwegner** [dangwu/Octal#122]
Been getting this for the past couple days... if I manually swipe down to refresh the feed, I am getting content from a few days ago. 

![](https://media.giphy.com/media/jUnJKYCrL18blIg2l8/giphy.gif)

It seems to happen with various regularity. Sometimes it takes 20+ refreshes, other times it’s pretty much every time.

**Comment by mtamassia** [comment]
I just installed and purchased the app and I am having the exact same issue. 

Most of the time it defaults to the wrong/outdated list upon opening the app, if I refresh multiple times, exactly like @josephwegner described, it eventually shows the correct listing (that matches yc website).

Please address this ASAP.

**Comment by dangwu** [comment]
I am confident that this is an issue with the API, as this only started
happening within the last few days. I’ve contacted HN for
further assistance and I’ll keep you posted.

Thanks!

**Comment by dangwu** [comment]
The HN admin is aware of the issue and working on it. They’ve received
reports from other API users as well.

**Comment by pcr910303** [comment]
@dangwu This issue hasn’t just happened for the last few days; It was a recurring problem even when the APIs were going good.

Granted, this is happening much more as the APIs are having issues; but my understanding of this issue is that Octal sometimes return an outdated list of cached articles when the HN API didn’t return a proper response.

One method I have found to cause this issue trigger is to refresh again while the previous request hasn’t finished; that usually results in an old article list.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zx8** [comment]
Not sure if this is relevant, but I'll throw in my personal experience, but may potentially be the root cause of this issue...

This only started happening to me (last week) _after_ I upvoted a post for the first time ever on the app. This may have caused the page to be cached and it is now constantly, and seemingly arbitrarily, being shown after refreshes, pretty much exactly as the OP describes.

Just something to consider!

**Comment by dangwu** [comment]
Interesting idea, but upvoting and fetching stories from the API are
totally unrelated. Daniel (the HN API admin) has already concluded that the
API is at fault, and he's investigating. No need for more ideas :P

**Comment by dangwu** [comment]
This is now resolved on HN's side!
