### ISSUE TITLE
[Feature] View answers to user's comments

### ISSUE THREAD

**Issue by bclnr** [dangwu/Octal#156]
It would be really useful to be able see the answers to the user's comments. Maybe with a way to jump back into the thread.
Ideally inside the app it would show when there are new messages.

**Comment by dangwu** [comment]
Can you elaborate? A little lost here

**Comment by bclnr** [comment]
Sorry, I mean to see the comments posted below mines.
When somebody comments directly below something I posted, I'd like to notice and read it. 

For example if the user comments with a question, or an argument, it's useful to read what others reply to that.

**Comment by dangwu** [comment]
Ah I see. There is no notifications API for something like that. I'd have
to implement a server-side thing to achieve that, and it'd be really messy,
probably involving polling. Also, I remember reading that HN purposefully
does not notify people of comment replies in order to discourage arguments
- so I'd like to respect that.

**Comment by bclnr** [comment]
I see, that makes sense. Thanks for the app.
